### ISSUE TITLE
Change of workflow

### ISSUE THREAD

**Issue by mfasDa** [mfasDa/indicoCheckin#13]
- standard case: code is read successfully, person is not yet checked
  in and person has already paid
  --> no message box appears, but it beeps once, checks the person in
  and prints the ticket. If error while printing, you can click on the
  print button to retry printing.
- case: person has not yet paid
  --> it beeps twice, you can set person to paid and check him in and
  print the ticket
- case: ticket cannot be read, or person is already checked in, or
  other error
  --> three beeps, you can then search the person manually, or print
  the ticket again, if already checked in

--> so in standard case, for each person, only one click is needed,
namely to start the code reading

**Comment by mfasDa** [comment]
Workflow partially implemented. Only one click is needed in standard case to checkin the user with a ticket.

**Comment by mfasDa** [comment]
The application now does beeping in case of errors. I strongly recommend to rethink this strategy.

**Comment by zwound40** [comment]
in my setup, i don't get a beep. in the window, additionally, there should be a warning, that an error occured.

**Comment by mfasDa** [comment]
Fixes in the program: 
- Beeping is now done using a timer thread.
- Registrant info is correctly displayed
  -Thus an error message is given in case the ticket is invalid. The registar should still confirm that he is aware that an exceptional behaviour happened.

I close the ticket now.
